export enum Major {
  Barber = 'barber',
  HairSalon = 'hairSalon',
  Spa = 'spa',
  MassageTherapist = 'massageTherapist',
  Dentist = 'dentist',
  GeneralDoctor = 'generalDoctor',
  Pediatrician = 'pediatrician',
  Dermatologist = 'dermatologist',
  Psychologist = 'psychologist',
  Physiotherapist = 'physiotherapist',
  PersonalTrainer = 'personalTrainer',
  YogaInstructor = 'yogaInstructor',
  TattooArtist = 'tattooArtist',
  MusicTeacher = 'musicTeacher',
  LanguageTutor = 'languageTutor',
  Photographer = 'photographer',
  Videographer = 'videographer',
  MakeupArtist = 'makeupArtist',
  NailTechnician = 'nailTechnician',
  PetGroomer = 'petGroomer',
  Veterinarian = 'veterinarian',
  AutoMechanic = 'autoMechanic',
  DrivingInstructor = 'drivingInstructor',
  HomeCleaner = 'homeCleaner',
  Electrician = 'electrician',
  Plumber = 'plumber',
  Carpenter = 'carpenter',
  Locksmith = 'locksmith',
  ApplianceRepair = 'applianceRepair',
  EventPlanner = 'eventPlanner',
  LegalAdvisor = 'legalAdvisor',
  FinancialConsultant = 'financialConsultant',
  CareerCoach = 'careerCoach',
}

/**
 * Optimized Configuration
 */
export const EMOJI_MAP: Record<string, string> = {
  all: '✨',
  [Major.Barber]: '💇‍♂️',
  [Major.HairSalon]: '💇‍♀️',
  [Major.Spa]: '🧖‍♀️',
  [Major.Dentist]: '🦷',
  [Major.PersonalTrainer]: '🏋️',
  [Major.YogaInstructor]: '🧘‍♂️',
  [Major.TattooArtist]: '🎨',
  [Major.GeneralDoctor]: '👨‍⚕️',
  [Major.MassageTherapist]: '💆',
  [Major.Pediatrician]: '👶',
  [Major.Dermatologist]: '🧴',
  [Major.Psychologist]: '🧠',
  [Major.Physiotherapist]: '🦴',
  [Major.MusicTeacher]: '🎵',
  [Major.LanguageTutor]: '🗣️',
  [Major.Photographer]: '📸',
  [Major.Videographer]: '🎥',
  [Major.MakeupArtist]: '💄',
  [Major.NailTechnician]: '💅',
  [Major.PetGroomer]: '🐶',
  [Major.Veterinarian]: '🩺',
  [Major.AutoMechanic]: '🔧',
  [Major.DrivingInstructor]: '🚗',
  [Major.HomeCleaner]: '🧹',
  [Major.Electrician]: '💡',
  [Major.Plumber]: '🚰',
  [Major.Carpenter]: '🪚',
  [Major.Locksmith]: '🔑',
  [Major.ApplianceRepair]: '🛠️',
  [Major.EventPlanner]: '🎉',
  [Major.LegalAdvisor]: '⚖️',
  [Major.FinancialConsultant]: '💼',
  [Major.CareerCoach]: '🧭',
};
